In [106]:
import numpy as np

In [125]:
from collections import deque

with open('input.txt') as f:
    M = tuple(map(lambda x: tuple(x.strip()), f.readlines()))

assert len(M) == len(M[0])  # square matrix
n = len(M)

VISITED = set()
V = {}
Q = deque([])

for i in range(n):
    for j in range(n):
        if M[i][j] == 'S':
            p = i,j,0,0,0           # 3rd field is the distance from S
            VISITED.add(p)
            Q.append(p)

def update_structures(p_i, p_j, p_dist, replica_i, replica_j):
    p = p_i, p_j, p_dist, replica_i, replica_j
    if p not in VISITED:

        #if p_dist in [65, 65+n, 65+n*2, 65+n*3, 65+n*4, 65+n*5]:  
        if p_dist in [65, 65+n, 65+n*2, 65+n*3, 65+n*4]: 
            if tuple([p_dist, replica_i, replica_j]) not in V:
                V[tuple([p_dist, replica_i, replica_j])] = set()
            V[tuple([p_dist, replica_i, replica_j])].add(tuple([p_i, p_j]))

        VISITED.add(p)
        Q.append(p)

while Q:

    p_i, p_j, p_dist, replica_i, replica_j = Q.popleft()

    # if p_dist > 65+n*5:       uncomment if you want to wait 
    if p_dist > 65+n*4: 
        continue
    
    if p_i-1 == -1 and M[n-1][p_j] != '#':
        update_structures(n-1, p_j, p_dist+1, replica_i-1, replica_j)
    elif M[p_i-1][p_j] != '#':
        update_structures(p_i-1, p_j, p_dist+1, replica_i, replica_j)

    if p_i+1 == n and M[0][p_j] != '#': 
        update_structures(0, p_j, p_dist+1, replica_i+1, replica_j)
    elif M[p_i+1][p_j] != '#':
        update_structures(p_i+1, p_j, p_dist+1, replica_i, replica_j)

    if p_j-1 == -1 and M[p_i][n-1] != '#': 
        update_structures(p_i, n-1, p_dist+1, replica_i, replica_j-1)
    elif M[p_i][p_j-1] != '#':
        update_structures(p_i, p_j-1, p_dist+1, replica_i, replica_j)

    if p_j+1 == n and M[p_i][0] != '#': 
        update_structures(p_i, 0, p_dist+1, replica_i, replica_j+1)
    elif M[p_i][p_j+1] != '#':
        update_structures(p_i, p_j+1, p_dist+1, replica_i, replica_j)


M0 = np.zeros((11,11))
M1 = np.zeros((11,11))
M2 = np.zeros((11,11))
M3 = np.zeros((11,11))
M4 = np.zeros((11,11))
#M5 = np.zeros((11,11))         uncomment if you want to wait 

for k in V:

    if k[0] == 65:          M0[k[1]+5,k[2]+5] = len(V[k])
    elif k[0] == 65+n:      M1[k[1]+5,k[2]+5] = len(V[k])
    elif k[0] == 65+n*2:    M2[k[1]+5,k[2]+5] = len(V[k])
    elif k[0] == 65+n*3:    M3[k[1]+5,k[2]+5] = len(V[k])
    elif k[0] == 65+n*4:    M4[k[1]+5,k[2]+5] = len(V[k])
    #elif k[0] == 65+n*5:    M5[k[1]+5,k[2]+5] = len(V[k])
    else:                   raise AssertionError()

'\nfor dist in [65,65+n,65+n*2,65+n*3,65+n*4,65+n*5]:\n    print(dist)\n    for k in V:\n        if k[0] == dist:\n            print(k[1],k[2], len(V[k]))\n    print()\n'

la matrice quadrata ha dimensione 131

per sforarla la prima volta servono 65 passi

per sforare le nuove matrici poi servono ogni volta 131 passi

"per magia" il nostro numero di passi è esattamente uguale a 65 + 131 * 202300

In [107]:
(26501365 - 65) / 131

202300.0

questo è il numero di celle raggiungibili in ogni matrice dopo 65 + 131 * n passi con n = 0

In [126]:
M0

array([[3734.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
           0.,    0.],
       [   0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
           0.,    0.],
       [   0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
           0.,    0.],
       [   0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
           0.,    0.],
       [   0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
           0.,    0.],
       [   0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
           0.,    0.],
       [   0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
           0.,    0.],
       [   0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
           0.,    0.],
       [   0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
           0.,    0.],
       [   0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
           0.,    0.],
       [   0.,    0.,    0.,    0.,    0.,    0.,    0.,    

questo è il numero di celle raggiungibili in ogni matrice dopo 65 + 131 * n passi con n = 1

In [127]:
M1

array([[7354., 5538.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
           0., 5558.],
       [5555.,  941.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
           0.,  936.],
       [   0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
           0.,    0.],
       [   0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
           0.,    0.],
       [   0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
           0.,    0.],
       [   0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
           0.,    0.],
       [   0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
           0.,    0.],
       [   0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
           0.,    0.],
       [   0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
           0.,    0.],
       [   0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
           0.,    0.],
       [5541.,  937.,    0.,    0.,    0.,    0.,    0.,    

questo è il numero di celle raggiungibili in ogni matrice dopo 65 + 131 * n passi con n = 2

In [ ]:
M2

In [108]:
with open('mat_before_before.txt') as f:
    input = tuple(map(lambda x: x.strip(), f.readlines()))

M = np.zeros((11,11),dtype=np.int64)

In [109]:
for l in input:
    i,j,value = list(map(lambda x: int(x), l.split()))
    M[i+5][j+5] = value
M

array([[   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0],
       [   0,    0,    0,    0,  925, 5541,  937,    0,    0,    0,    0],
       [   0,    0,    0,  925, 6459, 7354, 6444,  937,    0,    0,    0],
       [   0,    0,    0, 5558, 7354, 7362, 7354, 5538,    0,    0,    0],
       [   0,    0,    0,  936, 6461, 7354, 6456,  941,    0,    0,    0],
       [   0,    0,    0,    0,  936, 5555,  941,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0]])

questo è il numero di celle raggiungibili in ogni matrice dopo 65 + 131 * n passi con n = 3

In [ ]:
M3

In [110]:
with open('mat_before.txt') as f:
    input = tuple(map(lambda x: x.strip(), f.readlines()))

M = np.zeros((11,11),dtype=np.int64)

In [111]:
for l in input:
    i,j,value = list(map(lambda x: int(x), l.split()))
    M[i+5][j+5] = value
M

array([[   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0],
       [   0,    0,    0,    0,  925, 5541,  937,    0,    0,    0,    0],
       [   0,    0,    0,  925, 6459, 7354, 6444,  937,    0,    0,    0],
       [   0,    0,  925, 6459, 7354, 7362, 7354, 6444,  937,    0,    0],
       [   0,    0, 5558, 7354, 7362, 7354, 7362, 7354, 5538,    0,    0],
       [   0,    0,  936, 6461, 7354, 7362, 7354, 6456,  941,    0,    0],
       [   0,    0,    0,  936, 6461, 7354, 6456,  941,    0,    0,    0],
       [   0,    0,    0,    0,  936, 5555,  941,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0]])

In [112]:
np.sum(M)

180683

ricaviamo, guardando la matrice, una formula per calcolare il numero totale di celle raggiungibili dopo 65 + 131 * n passi

In [113]:
n=3
936*n + 925*n + 937*n + 941*n + 5558 + 5541 + 5538 + 5555 + 6461*(n-1) + 6459*(n-1) + 6444*(n-1) + 6456*(n-1) + 7354 * (n**2) + 7362 * ((n-1)**2)

180683

questo è il numero di celle raggiungibili in ogni matrice dopo 65 + 131 * n passi con n = 4

In [ ]:
M4

In [114]:
with open('mat_after.txt') as f:
    input = tuple(map(lambda x: x.strip(), f.readlines()))

M = np.zeros((11,11),dtype=np.int64)

In [115]:
for l in input:
    i,j,value = list(map(lambda x: int(x), l.split()))
    M[i+5][j+5] = value
M

array([[   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0],
       [   0,    0,    0,    0,  925, 5541,  937,    0,    0,    0,    0],
       [   0,    0,    0,  925, 6459, 7354, 6444,  937,    0,    0,    0],
       [   0,    0,  925, 6459, 7354, 7362, 7354, 6444,  937,    0,    0],
       [   0,  925, 6459, 7354, 7362, 7354, 7362, 7354, 6444,  937,    0],
       [   0, 5558, 7354, 7362, 7354, 7362, 7354, 7362, 7354, 5538,    0],
       [   0,  936, 6461, 7354, 7362, 7354, 7362, 7354, 6456,  941,    0],
       [   0,    0,  936, 6461, 7354, 7362, 7354, 6456,  941,    0,    0],
       [   0,    0,    0,  936, 6461, 7354, 6456,  941,    0,    0,    0],
       [   0,    0,    0,    0,  936, 5555,  941,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0]])

In [116]:
np.sum(M)

298530

In [117]:
n=4
936*n + 925*n + 937*n + 941*n + 5558 + 5541 + 5538 + 5555 + 6461*(n-1) + 6459*(n-1) + 6444*(n-1) + 6456*(n-1) + 7354 * (n**2) + 7362 * ((n-1)**2)

298530

questo è il numero di celle raggiungibili in ogni matrice dopo 65 + 131 * n passi con n = 5

In [ ]:
M5

In [118]:
with open('mat_after_after.txt') as f:
    input = tuple(map(lambda x: x.strip(), f.readlines()))

M = np.zeros((11,11),dtype=np.int64)

In [119]:
for l in input:
    i,j,value = list(map(lambda x: int(x), l.split()))
    M[i+5][j+5] = value
M

array([[   0,    0,    0,    0,  925, 5541,  937,    0,    0,    0,    0],
       [   0,    0,    0,  925, 6459, 7354, 6444,  937,    0,    0,    0],
       [   0,    0,  925, 6459, 7354, 7362, 7354, 6444,  937,    0,    0],
       [   0,  925, 6459, 7354, 7362, 7354, 7362, 7354, 6444,  937,    0],
       [ 925, 6459, 7354, 7362, 7354, 7362, 7354, 7362, 7354, 6444,  937],
       [5558, 7354, 7362, 7354, 7362, 7354, 7362, 7354, 7362, 7354, 5538],
       [ 936, 6461, 7354, 7362, 7354, 7362, 7354, 7362, 7354, 6456,  941],
       [   0,  936, 6461, 7354, 7362, 7354, 7362, 7354, 6456,  941,    0],
       [   0,    0,  936, 6461, 7354, 7362, 7354, 6456,  941,    0,    0],
       [   0,    0,    0,  936, 6461, 7354, 6456,  941,    0,    0,    0],
       [   0,    0,    0,    0,  936, 5555,  941,    0,    0,    0,    0]])

In [120]:
np.sum(M)

445809

In [121]:
n=5
936*n + 925*n + 937*n + 941*n + 5558 + 5541 + 5538 + 5555 + 6461*(n-1) + 6459*(n-1) + 6444*(n-1) + 6456*(n-1) + 7354 * (n**2) + 7362 * ((n-1)**2)

445809

applicazione della formula per ottenere ciò che ci chiede il problema

In [122]:
n=202300
936*n + 925*n + 937*n + 941*n + 5558 + 5541 + 5538 + 5555 + 6461*(n-1) + 6459*(n-1) + 6444*(n-1) + 6456*(n-1) + 7354 * (n**2) + 7362 * ((n-1)**2)

602259568764234